### ISSUE TITLE
Image Uploading Interface Feedback List

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#1]
- [x] The columns should autosize to cover the entire image width based on the number of columns required

- [x] Change the label Floor to Rows

- [x] Change the label Unit/Floor to Columns

- [x] Change the instruction "Input how many floor and unit/floor" to "Enter grid specifications" 

- [x] We have to provide landscape and portrait orientation function

- [x] Provide space between the buttons

- [x] We need to allow the work to be saved for future work in case they cannot complete the all the linking

**Comment by benjaminl83** [comment]
@chuanhiang 
The following is not fulfilled yet. Please advise if they are still relevant
- [ ] The columns should autosize to cover the entire image width based on the number of columns required
- [ ] Change the instruction "Input how many floor and unit/floor" to "Enter grid specifications" 
- [ ] We have to provide landscape and portrait orientation function

**Comment by Ponpimonk** [comment]
@benjaminl83 @chuanhiang This one I assume interaktiv will test and close?

**Comment by chuanhiang** [comment]
All functions are delivered though not int he exact description.
