### ISSUE TITLE
Cell cursor is showing both cell when only highlighting one

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#15]
![image](https://user-images.githubusercontent.com/9443519/28558936-cd1bd4d8-7146-11e7-85a0-6d05ed54f7bd.png)

**Comment by chuanhiang** [comment]
![image](https://user-images.githubusercontent.com/9443519/28559293-862bfed4-7148-11e7-8149-e26af050dccf.png)

@purnomoeko 
Just another way this bug is showing up.

Thanks.

**Comment by chuanhiang** [comment]
![image](https://user-images.githubusercontent.com/9443519/28559466-43905c9a-7149-11e7-9fb7-46fdd45aa94b.png)

@purnomoeko 
The lines at the end are truncated and the cell attributes are not showing. I think it is because the cell is too long. We have allow the cell attributes to show even if the width is too long.

Thanks.

**Comment by benjaminl83** [comment]
Resolved, this is because of cell overlapping
