### ISSUE TITLE
Change the Thank You Email Template as per the Email

### ISSUE THREAD

**Issue by VeenaKurady** [Interaktivtechnology/Raimon-Web#20]
Change the Thank You Email Template as per the Email

**Comment by benjaminl83** [comment]
Thank you email generated
![image](https://user-images.githubusercontent.com/18274902/29524538-ab239b5e-86c2-11e7-8650-dc92fc7cc6cc.png)

**Comment by chuanhiang** [comment]
Ben, I just

**Comment by chuanhiang** [comment]
@benjaminl83 @VeenaKurady 
I've justed save and send an email for this opportunity https://rl--full.cs31.my.salesforce.com/006p0000004leT0?srPos=1&srKp=006 

The activity history has it but the email was not received in my mailbox.

Thanks.

**Comment by benjaminl83** [comment]
Email can be sent with the correct header and footer from Project
