### ISSUE TITLE
Property Management Not Working in the Home Page

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#27]
@purnomoeko @benjaminl83 Please refer to this link the property management on the menu is not working

https://raimon-land-sales-matrix.firebaseapp.com/building
![image](https://user-images.githubusercontent.com/18274902/29312723-44f55b70-81e9-11e7-8a69-c4367fcc8f7b.png)

**Comment by benjaminl83** [comment]
@Ponpimonk 
Can you try to clear browser cache and see if it will work?
To clear cache:
1. Go to Chrome History (Ctrl H)
![image](https://user-images.githubusercontent.com/18274902/29313146-fdb8a15c-81ea-11e7-9327-96871dd2f24e.png)

Click "Clear browsing Data", Select "Cached images and files"
![image](https://user-images.githubusercontent.com/18274902/29313192-3ef5a8f4-81eb-11e7-97e9-f0e917979ce0.png)
Then click "Clear browsing data"

**Comment by Ponpimonk** [comment]
The menu property management is working now.
