### ISSUE TITLE
Opprotunity check duplicate project-account-product

### ISSUE THREAD

**Issue by VeenaKurady** [Interaktivtechnology/Raimon-Web#28]
Check Duplicate Project-Account-Product for the Oppturnity Before Insert Update 
- Issue raised by Eko

**Comment by VeenaKurady** [comment]
*Applies only to Not Contacted, Contacted, TM Active, Qualified, Quotes issued, Under Negotiation Opportunity Stage

**Comment by benjaminl83** [comment]
Will confirm this logic with Raimon tomorrow

**Comment by benjaminl83** [comment]
@VeenaKurady 
You need to change this logic to NOT consider the product:

e.g. Project =  "The Lofts Silom", Account = "Ben"
Existing Opportunity = Loft Silom > Ben - Sales Status = Qualified. No product tagged
User try to create 2nd Opportunity in The Lofts Silom for Ben -> MUST FAIL

However if:
Existing Opportunity = Loft Silom > Ben - Sales Status = Booked
User try to create 2nd Opportunity in The Lofts Silom for Ben -> ALLOW

**Comment by benjaminl83** [comment]
@chuanhiang @VeenaKurady 
This requirement is dropped, I need you to undo this change
