### ISSUE TITLE
Update Product Trigger to push data to external site

### ISSUE THREAD

**Issue by VeenaKurady** [Interaktivtechnology/Raimon-Web#29]
After Update Product, trigger to push data to external site
https://us-central1-raimon-land-sales-matrix.cloudfunctions.net/salesforce/update-product
- Assigned by Eko

**Comment by VeenaKurady** [comment]
https://us-central1-raimon-land-sales-matrix.cloudfunctions.net/webhook/update-product

**Comment by benjaminl83** [comment]
@purnomoeko 
Please assess and close
