### ISSUE TITLE
Text format and colour of the cell number

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#3]
@purnomoeko 

- [ ] Change the cell numbering to R1C1, R2C1 and so on

- [x] Change the text colour to white when it is a black background; OR

- [x] Ask them to upload only the outline of the silhouette

We might want to ask them to produce only the outline of the building silhouette. Please let me know if this is a preferred option.

**Comment by benjaminl83** [comment]
Cell numbering format has changed to *Floor*-*Sequence*
Requirement changed refer to https://github.com/Interaktivtechnology/Raimon-Web/issues/63
