### ISSUE TITLE
Unable to pull out the sizing bar once it gets thrown out from the frame

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#31]
@benjaminl83 @purnomoeko Can you make sure we can pull out the cell adjustment bar eventhough it's been thrown out of the matrix frame? It's very difficult to continue if this is not fixed.
![image](https://user-images.githubusercontent.com/30112738/29359202-df5fb890-82a7-11e7-969f-f32a62e9b3c1.png)

https://raimon-land-sales-matrix.firebaseapp.com/building/new

**Comment by purnomoeko** [comment]
in latest version right clicking the cell will bring the cell attribute near to the cell.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please close this issue if you have tested it.

Thanks.

**Comment by benjaminl83** [comment]
@Ponpimonk 
issue is resolved under https://github.com/Interaktivtechnology/Raimon-Web/issues/18

**Comment by Ponpimonk** [comment]
Ok.
