### ISSUE TITLE
Error notification

### ISSUE THREAD

**Issue by Wichudadej** [Interaktivtechnology/Raimon-Web#32]
We are on testing fill in the account information in ipad. While we search an email for "panatp@yahoo.com" this email is existing in sandbox but the error shows that "Not found, Email can't be found. Please create new account". So please kindly check and let us know. Thank you.

**Comment by benjaminl83** [comment]
@purnomoeko 
Please let us know which version is this resolved.

**Comment by benjaminl83** [comment]
Please try this on ver 0.4.0
