### ISSUE TITLE
New Prospect Page Error 

### ISSUE THREAD

**Issue by Wichudadej** [Interaktivtechnology/Raimon-Web#33]
We found the error from testing the new prospect page as per list below:

1. Email does not exists in sandbox but the system shows the notification that "An Error occured "FIELD_CUSTOM_VALIDATION_EXCEPTION - This Account is duplicated. - Account".
![image](https://user-images.githubusercontent.com/30311578/29360907-450db884-82af-11e7-8709-01b5a249b4be.png)

2.  Email exists in sandbox but the system shows the notification that "NOT FOUND, Emil can't be found. Please create new account"
![image](https://user-images.githubusercontent.com/30311578/29361034-e8d6fff2-82af-11e7-9267-b1611b6afee0.png)

3. After created the new opp. in iPad, the new  opp. was not shown in sandbox.

**Comment by benjaminl83** [comment]
@purnomoeko 
Let us know which version is this resolved

**Comment by purnomoeko** [comment]
@chuanhiang  @benjaminl83  @VeenaKurady This issue has come when the first name and last name exist in database (even though different email address). And this logic is exist in salesforce trigger, do we need that logic here?

**Comment by VeenaKurady** [comment]
Already(not devleoped by Interaktiv) Trigger exists to disallow Account from being created if firstname and last name matches or email id matches to prevent duplication of Record

**Comment by benjaminl83** [comment]
@Wichudadej 
In SF backend its not created  yet
![image](https://user-images.githubusercontent.com/18274902/29557774-b82fca9e-875c-11e7-99c7-2fd5078b4a2d.png)
