### ISSUE TITLE
Save mode - Sales Matrix Firebase App.

### ISSUE THREAD

**Issue by Wichudadej** [Interaktivtechnology/Raimon-Web#34]
When we finished to draw the new building layout, we can click save button but the building is not in the list.

**Comment by chuanhiang** [comment]
@Wichudadej 

This version has a limit of 10 building. Please wait for the next version to be released.

Thanks.

**Comment by Wichudadej** [comment]
@chuanhiang 

Thank you for your clarification. 

Best regards,

**Comment by benjaminl83** [comment]
@Wichudadej 
Now user can save beyond the previous limit of 10

**Comment by Wichudadej** [comment]
Save mode for beyond the limit 10 buildings work fine. Thank you.
![image](https://user-images.githubusercontent.com/30311578/29442523-45e8e316-83fc-11e7-8b6d-8d4a6d250110.png)
