### ISSUE TITLE
Only Active Project should be shown in the search result when creating new building

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#39]
@purnomoeko 
![image](https://user-images.githubusercontent.com/9443519/29411200-5c8de2b8-8386-11e7-8b95-3030a25ca0e1.png)

When the project is inactivated all the buildings belonging to the project will not be shown in the web app and the mobile app.

Thanks.

**Comment by benjaminl83** [comment]
Resolved
