### ISSUE TITLE
Security Error - Inactivating a user should have immediate effect once navigating to another page

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#43]
Once user is inactivated, when user navigate to another page, it should throw the user out

**Comment by benjaminl83** [comment]
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by purnomoeko** [comment]
This issue unlikely to happen, if you want to deactivate your current login you should ask another person to disable your account.

**Comment by benjaminl83** [comment]
Confirmed by Chuan
