### ISSUE TITLE
Undo function in building configuration does not work properly

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#45]
Undo function when clicked undo all the steps to the beginning.

Thanks.

**Comment by purnomoeko** [comment]
@chuanhiang can you demo it? I can do it perfectly from here.

**Comment by benjaminl83** [comment]
Tested working but not all the time, issue opened as https://github.com/Interaktivtechnology/Raimon-Web/issues/64
