### ISSUE TITLE
Publish  This Building --> Cannot click cancel

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#49]
@benjaminl83 @purnomoeko Unable to click cancel for Publish this building
![image](https://user-images.githubusercontent.com/30112738/29508262-0c18f1b0-867e-11e7-8d30-e05966910554.png)

**Comment by purnomoeko** [comment]
@benjaminl83 just deployed please check

**Comment by Ponpimonk** [comment]
@benjaminl83 @purnomoeko Ok it is working now
