### ISSUE TITLE
Unable to add a new user to Firebase

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#51]
@benjaminl83 @purnomoeko Unable to add a new user to Firebase

https://raimon-land-sales-matrix.firebaseapp.com/user/new

![image](https://user-images.githubusercontent.com/30112738/29514777-ee195b80-8693-11e7-9e37-d5a1fa44bb2a.png)

**Comment by benjaminl83** [comment]
@fransjosua 
The user probably got created but does not appear on the user list.
I tried creating wichuda1@raimonland.com, it got saved, but didn't appear on the list.

**Comment by purnomoeko** [comment]
Wichuda@raimonland has been registered in the backend but not showing here. We should update this list @fransjosua.

**Comment by benjaminl83** [comment]
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by benjaminl83** [comment]
@Ponpimonk 
Resolved, But since last name is mandatory, we are displaying in LastName FirstName format as we are sorting by LastName.

**Comment by Ponpimonk** [comment]
Can add now
