### ISSUE TITLE
Blocked period

### ISSUE THREAD

**Issue by Wichudadej** [Interaktivtechnology/Raimon-Web#52]
While I am testing the log in web app. I tried to log in many times with incorrect password and the system shows me an error so how long it takes for this blocked ? 

![image](https://user-images.githubusercontent.com/30311578/29514743-d0fc20d2-8693-11e7-9983-d53236f65da7.png)

**Comment by purnomoeko** [comment]
Usually it will take about 15 minutes before trying another login..

**Comment by Wichudadej** [comment]
Noted and thank you for your information.
