### ISSUE TITLE
How come Width is located at the bottom?

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#53]
@benjaminl83 @purnomoeko  How come Width is located at the bottom?

https://raimon-land-sales-matrix.firebaseapp.com/building/edit/-Kro1z3apqp31tZNnPCJ

![image](https://user-images.githubusercontent.com/30112738/29515903-825024c4-8698-11e7-8f3e-47c2a933927a.png)

**Comment by purnomoeko** [comment]
@ponpimonk it's sorted alphabetically we can change the order if you want

**Comment by benjaminl83** [comment]
@purnomoeko 
Preference is for width to be on top, user has a preference to work with the width, then the height, then moving left and right

**Comment by Ponpimonk** [comment]
OK
