### ISSUE TITLE
New building layout - Block creation of building with blank project name

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#54]
@purnomoeko 
When building has no project name, the layout does not load
We should validate that building name is mandatory when creating new building layout

**Comment by benjaminl83** [comment]
@purnomoeko 
Make Project field mandatory

**Comment by chuanhiang** [comment]
@purnomoeko 
Practically user can still work with the building and retrospectively select the project name but when saving you get a non-stop running saving mode.

![image](https://user-images.githubusercontent.com/9443519/29851350-2b14b614-8d66-11e7-84e3-925b10671e29.png)

**Comment by chuanhiang** [comment]
Working now.
![image](https://user-images.githubusercontent.com/9443519/29866042-bcf6f6ee-8da9-11e7-8c61-d535a6710a7e.png)
