### ISSUE TITLE
Publishing - Unpublished, Mobile, Webapp, Both should prompt error when no change is actually made

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#55]

**Comment by benjaminl83** [comment]
As requested by Chuan

**Comment by chuanhiang** [comment]
@purnomoeko 

The system doesn't show any error message when the word entered doesn't match. We should show the error messages accordingly.

1. If the word entered is mispelled the error message should say, "The word entered is not spelt correctly and it is also case sensitive. Please try again."
2. If the word is spelt correctly we must match the case (case sensitive) if only the case is not matched we show the error message "The word entered is spelt correctly but it is case sensitive" Please try again."

**Comment by benjaminl83** [comment]
Tested with error as show if incorrect entry made
![image](https://user-images.githubusercontent.com/18274902/29852306-ef866592-8d6b-11e7-9652-408f61d4c4ee.png)
