### ISSUE TITLE
Brochure Email - Merge fields from Salesforce records

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#57]
@VeenaKurady 
Refer to the screenshot
![image](https://user-images.githubusercontent.com/18274902/29526404-35eb5e7a-86c8-11e7-88a5-88a4c73483c5.png)

The Lofts Silom should come from the Opportunity Project name
The signature should show: 
- Opportunity owner name
- Opportunity owner Role
- Opportunity owner department
- Opportunity owner Phone number
- Opportunity owner Fax number
- Opportunity owner email address

**Comment by Ponpimonk** [comment]
@Wichudadej  Please close after N'Tig finish testing

**Comment by benjaminl83** [comment]
@Ponpimonk @Wichudadej 
I will be closing this issue. Again, you need to go into this links in sandbox to put in the "Generic wordings for Thank you letter"
https://rl--full.cs31.my.salesforce.com/00Xp0000000Ql4g?setupid=CommunicationTemplatesEmail
https://rl--full.cs31.my.salesforce.com/00Xp0000000Ql4l?setupid=CommunicationTemplatesEmail

**Comment by Ponpimonk** [comment]
OK
