### ISSUE TITLE
Opportunity - When updating Notification to "Both" only thank you email is sent out

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#61]
@VeenaKurady 
Both Thank you email and Brochures must be sent out.
And the brochure email must have the attached Brochure and Factsheet pdfs.

I only received this
![image](https://user-images.githubusercontent.com/18274902/29543861-d84c11fc-8716-11e7-9331-4de2cc84893c.png)

**Comment by VeenaKurady** [comment]
issue solved

**Comment by benjaminl83** [comment]
confirmed.
2 emails are generated with the correct header and footers from the project
![image](https://user-images.githubusercontent.com/18274902/29697714-67bf4dea-8983-11e7-9324-b7395ad527b5.png)
