### ISSUE TITLE
Should be able to retain the grid while changing the background image

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#62]
Should be able to retain the grid while changing the background image

![image](https://user-images.githubusercontent.com/30112738/29546816-aff78a24-8720-11e7-9843-1b5c532b91b1.png)

**Comment by benjaminl83** [comment]
@Ponpimonk 
The grid is drawn over the image cannot retain its attributes when you change the image

**Comment by Ponpimonk** [comment]
@benjaminl83 Please explain to me when we skype on Wed 30TH Aug. Thanks.

**Comment by Ponpimonk** [comment]
OK understand no background change and retain the grids
