### ISSUE TITLE
Undo last change skips the step some times

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#64]
@benjaminl83 @purnomoeko  Undo last change skips the step some times

**Comment by benjaminl83** [comment]
@purnomoeko 
We tried to delete 3 cells
![image](https://user-images.githubusercontent.com/18274902/29547385-473ad6a6-872c-11e7-9a09-edd890cc5076.png)

Then resize a cell
![image](https://user-images.githubusercontent.com/18274902/29547415-63714c9c-872c-11e7-88bd-1f30abf3f0ce.png)

Then moved it to a different place
![image](https://user-images.githubusercontent.com/18274902/29547426-75da381c-872c-11e7-8f26-57feb772308e.png)

Then tried to undo, it went back to the beginning
![image](https://user-images.githubusercontent.com/18274902/29547489-cfdfe398-872c-11e7-8ead-d82c9f21a3e9.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please test again as it now can undo step by step but not sure what is the limit of this function.

Thanks.

@purnomoeko 
Do you know how far the undo function can go?

Thanks.

**Comment by Ponpimonk** [comment]
OK
