### ISSUE TITLE
User Management - Unable to cilck USER without refreshing the page

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#66]
Unable to cilck USER without refreshing the page

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please retest again and hope you can close this issue.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29850926-977133bc-8d63-11e7-91f3-a15d72cf99c1.png)

**Comment by Ponpimonk** [comment]
OK :)
