### ISSUE TITLE
Publish layout - When set to mobile, user can still view the webapp.

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#67]
@benjaminl83 @purnomoeko When set to mobile, user can still view the webapp.

**Comment by benjaminl83** [comment]
@purnomoeko 
management user should not be able to access property management page for that matter
So when management user building query page, they should not be able to see this building to make a query

**Comment by benjaminl83** [comment]
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by chuanhiang** [comment]
@fransjosua
 
This is still not working.

Please login using:

Username: leoteng.ch@gmail.com
PW: interaktiv.1

User still can access property management.

Thanks.

**Comment by chuanhiang** [comment]
@benjaminl83 

Can we close this since Khun Ponpimon already closed #68?

Thanks.

**Comment by benjaminl83** [comment]
Confirmed
For a Mobile DM user

Trying to access the webapp will invoke the error like below
![image](https://user-images.githubusercontent.com/18274902/29852854-17e97d78-8d6f-11e7-92fc-70e2bdaf8f29.png)

**Comment by Ponpimonk** [comment]
ok
