### ISSUE TITLE
User Management - Non-Admin user should not see the user management at all

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#68]
Non-Admin user should not see the user management at all

![image](https://user-images.githubusercontent.com/30112738/29547824-ac1a3b08-8726-11e7-8b83-7e2055c53bb0.png)

**Comment by benjaminl83** [comment]
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by benjaminl83** [comment]
Resolved.
Logging in as management user I was not able to access user management page
![image](https://user-images.githubusercontent.com/18274902/29697547-5d1e383e-8982-11e7-888f-beae583ef857.png)

**Comment by Ponpimonk** [comment]
Test and ok
