### ISSUE TITLE
Publish Layout - Management should only see "Web" and "Both" and not "Unpublished"

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#69]
Management should only see "Web" and "Both" and not "Unpublished"

![image](https://user-images.githubusercontent.com/30112738/29548011-e16a1ef8-8727-11e7-9fa1-2072272dd117.png)

**Comment by benjaminl83** [comment]
@fransjosua 
Issue will be resolved with https://github.com/Interaktivtechnology/Raimon-Web/issues/68

**Comment by benjaminl83** [comment]
@purnomoeko 
Reassigned to you since Josua is not available

**Comment by benjaminl83** [comment]
@fransjosua 
Please check and resolve this

**Comment by chuanhiang** [comment]
@fransjosua 

Still not resolved.
![image](https://user-images.githubusercontent.com/9443519/29823833-65919226-8d02-11e7-95e5-a25525a4d212.png)

**Comment by chuanhiang** [comment]
@benjaminl83 
I removed the urgent label because I don't think it is a problem for management user to see unpublished buildings

**Comment by benjaminl83** [comment]
@Ponpimonk 
Accessing functions that are not allowed will bring the user to an error page
![image](https://user-images.githubusercontent.com/18274902/29853007-e92c7264-8d6f-11e7-96eb-bdeff6c4c52b.png)

**Comment by Ponpimonk** [comment]
@chuanhiang @benjaminl83 

Management can still access the unpublished building. Per below image, the left hand side is Admin access, the right hand side is Management access.

![image](https://user-images.githubusercontent.com/30112738/29856163-43cdfcf0-8d7b-11e7-8930-1b0b9379572d.png)

**Comment by Ponpimonk** [comment]
OK
