### ISSUE TITLE
Web app reporting - Cell display definition

### ISSUE THREAD

**Issue by benjaminl83** [Interaktivtechnology/Raimon-Web#70]
Please show the Transfer Status on the left side, Resale Status in the middle, Lease Status on the right
![image](https://user-images.githubusercontent.com/18274902/29612645-da8f4906-8834-11e7-8280-f51e1656f3f3.png)

Each status follows a 2 character code.

**Transfer status:**
Awaiting Hand Over = AW
Tentative = TN
Inspected 1 = I1
Inspected 2 = I2
Inspected 3 = I3
Inspected 3+ = I+
Paid 100% = PD
Recognized = RZ
moved-in wo transfer = MT
furniture-in wo transfer = FT
Transferred = TF
Final Notice = FN
Problem = PB

**Resale Status**
Not Available = NA
Available = AV
Reserved = RS
Booked = BK
Sold = SD

**Lease Status**
Not Available = NA
Available = AV
Reserved = RS
Booked = BK
Leased = LD

**Comment by benjaminl83** [comment]
@Ponpimonk 
The statuses are static coding and are not drawn from SF dynamically.
This means adding / removing statuses in SF will not dynamically change the statuses in the reporting system

**Comment by Ponpimonk** [comment]
@benjaminl83  To make sure I understand correctly, if I change the status from "Tentative" to "Transfer", the status will change from "TN" to "TF" automatically correct? 

However if I add a new status such as "test" to the list, no code will show.

Pls confirm.

**Comment by benjaminl83** [comment]
@purnomoeko 
Please check
![image](https://user-images.githubusercontent.com/18274902/29857493-824ea050-8d8b-11e7-966a-ac5179f5877e.png)

https://rl--full.cs31.my.salesforce.com/01t90000005hiPjAAI

I think the statuses were meant to show but the cell is too "Thin" to show it

**Comment by purnomoeko** [comment]
@benjaminl83 is this logic applied to layout builder as well?

**Comment by chuanhiang** [comment]
@Ponpimonk

Can we agree that this logic is not required when configuring the building?

Thanks.

**Comment by Ponpimonk** [comment]
@chuanhiang Can. But it will be displayed for Query right?

**Comment by chuanhiang** [comment]
@Ponpimonk 

Yes, it is already showing in the query function, please check.

Thanks.

**Comment by Ponpimonk** [comment]
OK
