### ISSUE TITLE
Query issue - Filter does not clear after changing criteria and applying again several times

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#71]
@benjaminl83 @purnomoeko 

![image](https://user-images.githubusercontent.com/30112738/29647762-0f6cde1a-88b5-11e7-8c9c-13c55ffa8f37.png)

**Comment by benjaminl83** [comment]
@Ponpimonk 
Please elaborate as we cannot replicate this problem on our side.
N.B.: Plug out from the projector as you do this please

**Comment by Ponpimonk** [comment]
@benjaminl83 I have set the filter a"Net Unit Price + Furntiure is larger or equal to 2,081,456.2.
The hi-light however covers the cell  with value 2,507,386.4.

https://raimon-land-sales-matrix.firebaseapp.com/query/edit/-KsHKKChvcYJn_pA9ibI/-KsHVQXsJEOsIG9d9saU

![image](https://user-images.githubusercontent.com/30112738/29769864-5c26d562-8c16-11e7-996d-1f4996186270.png)

**Comment by Ponpimonk** [comment]
@benjaminl83 

Filter 1: Title Deed price is larger than 15,000,000 THB.
Why is the cells with value below 15 MB are hi-lighted?

![image](https://user-images.githubusercontent.com/30112738/29770473-7e3c92ec-8c19-11e7-8636-c78e967dc4ca.png)

**Comment by Ponpimonk** [comment]
@benjaminl83 
Filter 1: Title Deed Price is larger than 15,000,000 AND Title Deed Price is lower than 16000000 = yellow
Filter 2: Title Deed price is larger or equal to 16,000,000 AND title Deed Price is lower than or equal to 17,000,000 

The result is now showing correctly.

![image](https://user-images.githubusercontent.com/30112738/29770695-7482c25c-8c1a-11e7-9a1e-eb4ed5271205.png)
