### ISSUE TITLE
New Building layout - After searching for the project and click on it, the screen becomes darker

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#73]
@benjaminl83 @purnomoeko @chuanhiang I am unable to continue with the grid building. After clicking on the project, it bounces me to this page right away without letting me choose the grids.

![image](https://user-images.githubusercontent.com/30112738/29648330-cbf928c0-88b7-11e7-9324-2305093f83da.png)

**Comment by chuanhiang** [comment]
@purnomoeko 

All pages are grayed out after user clicked the search button while trying to search for the project name.

Thanks.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please retest this again and there should be no problem trying to save a new building layout.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29850805-cc6ae60e-8d62-11e7-9d3b-2885ab9bc103.png)
![image](https://user-images.githubusercontent.com/9443519/29850833-f1a10d54-8d62-11e7-91c0-9860f4e4cc83.png)

**Comment by Ponpimonk** [comment]
OK
