### ISSUE TITLE
Web App Reporting - Product Cell - Information is not showing correctly. No area. Incorrect unit price.

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#74]
No Area is showing. It should have pulled from "Sold Area"
Unit price for sold product should pull from Net Unit + Furniture Price.

![image](https://user-images.githubusercontent.com/30112738/29648954-5e4673ba-88bb-11e7-8b20-1d5d8ba3f97e.png)

**Comment by benjaminl83** [comment]
@purnomoeko 
Please remove the "B" sign at the currency

**Comment by chuanhiang** [comment]
@purnomoeko 
We are left with this urgent issue and we can push for sign off.

Thanks.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please double check the information in the cell.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29857068-41e52c8e-8d89-11e7-854a-2c8cf52fcb02.png)

**Comment by Ponpimonk** [comment]
@benjaminl83 @purnomoeko @chuanhiang 

Why area is showing as unidentified?

![image](https://user-images.githubusercontent.com/30112738/29865611-26112e9c-8da0-11e7-9e24-44230fd0944e.png)

**Comment by Ponpimonk** [comment]
https://raimon-land-sales-matrix.firebaseapp.com/query/new/-KsmEFf75EN4akTlS8nC

**Comment by chuanhiang** [comment]
@Ponpimonk 

If you click the link again, you can see the results. Please remember to sync product if you make changes in the backend.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29866374-cc4e6676-8daa-11e7-9c05-27a7067a5d86.png)

**Comment by Ponpimonk** [comment]
Ok
![image](https://user-images.githubusercontent.com/30112738/29867185-ee4a29c8-8da4-11e7-8164-cc8fa56aae56.png)
