### ISSUE TITLE
Color Code - Should show the color instead of the coding

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#75]
@benjaminl83 @purnomoeko @chuanhiang 

![image](https://user-images.githubusercontent.com/30112738/29649850-3010744a-88c1-11e7-83e9-4285306f4f46.png)

**Comment by chuanhiang** [comment]
@purnomoeko 

We should allow the user to change the code as well so they can use colours from other colour apps.

Thanks.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Yes, we are showing the colour selected and also increased the option for selecting colours.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29851863-2b220884-8d69-11e7-957b-dc20ba2d28fe.png)

**Comment by Ponpimonk** [comment]
OK
