### ISSUE TITLE
Can we have the box float around

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#76]
@benjaminl83 @purnomoeko 
![image](https://user-images.githubusercontent.com/30112738/29649959-e0c93f42-88c1-11e7-8eec-72e303f39364.png)

**Comment by chuanhiang** [comment]
@purnomoeko 

Currently, the cells on the left are blocked by the filter box. Another suggestion is to allow the user to move the filter box to the left side. Floating is the best option.

Thanks.

**Comment by purnomoeko** [comment]
The box is too big for floating we have hide button to hide it, floating box is not a good choice for this case.

**Comment by purnomoeko** [comment]
The box is too big for floating we have hide button to hide it, floating box is not a good choice for this case.

**Comment by chuanhiang** [comment]
User is not able to see the query results with the filters at the same time. We need to have another way to allow them to see the results with the filters. Any suggestions?

**Comment by chuanhiang** [comment]
@Ponpimonk 

We have improved the interface by showing the colour code selected and also a legend on the top though not as ideal at the moment. Please close this issue if the implemented function is acceptable.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29851772-a9715e16-8d68-11e7-9834-def1aea3521a.png)

**Comment by Ponpimonk** [comment]
Ok as we can  hide the bar also
