### ISSUE TITLE
Filter coloring is not working properly

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#78]
@benjaminl83 @purnomoeko 
Filter 1: Room type = 1BR & Unit value < 3MB & Color = yellow
Filter 2: Room type = 2BRs, Color = Blue
But the picture is showing the color the other way around (Yellow for Filter 2 and Blue for Filter 1)

![image](https://user-images.githubusercontent.com/30112738/29650153-2b131ad6-88c3-11e7-8699-b3e025535c9d.png)

**Comment by Ponpimonk** [comment]
I need to lable this as critical as if this is not working ok, i cannot go live.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please check on your end and confirm if we can close this issue.
Filter 1 - Sales Status = Available
![image](https://user-images.githubusercontent.com/9443519/29823054-2100babc-8d00-11e7-93b2-f09264e9424e.png)

Filter 2 - Sales Status = Sold
![image](https://user-images.githubusercontent.com/9443519/29823188-805cba74-8d00-11e7-9f03-86b5b08bbf8f.png)

Filter 3 - Sales Status = Booked
![image](https://user-images.githubusercontent.com/9443519/29823254-b86da25c-8d00-11e7-834b-0c938548a0f8.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please take note that when Sales Status = Sold the values shown in the cell has not changed to the correct value. Please check the prices in Salesforce to verify the price. This issue is about filter colouring and now it is correct.

Thanks.

**Comment by Ponpimonk** [comment]
Filtering system is working ok.
