### ISSUE TITLE
Cell Building & Cell Attribute 

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#79]
@benjaminl83 @purnomoeko  Everytime i click CTRL and try to click the cell on the cell right next, the cell attribute always move and block that cell. This always happen when I try to work from left to right.

![image](https://user-images.githubusercontent.com/30112738/29768497-b0bf5a32-8c10-11e7-86c4-260794f2d0ef.png)

**Comment by benjaminl83** [comment]
@purnomoeko 
Is this behaviour customizable?

**Comment by chuanhiang** [comment]
@purnomoeko 

This issue does not happen to other buildings. You can try on this building and it does not happen.
https://raimon-land-sales-matrix.firebaseapp.com/building/edit/-KpV7LDsBM6ZMXj9WRYe

**Comment by chuanhiang** [comment]
@Ponpimonk 

You can try again, it is not happening to at least 4 buildings I've tested.

Thanks.

**Comment by Ponpimonk** [comment]
OK
