### ISSUE TITLE
Unable to get rid of the grid line

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#81]
@benjaminl83 @purnomoeko I have tried to expand the width but the grid line is still there. This will happen when I click "CTRL" and delete multiple cells together. If I delete the cell one-by-one and change the height and width of the main cell, the grid will be gone.

https://raimon-land-sales-matrix.firebaseapp.com/building/edit/-KscFy8f-dsMWv7e1Wj8

![image](https://user-images.githubusercontent.com/30112738/29769095-0a59ed6c-8c13-11e7-9ceb-00df9a321150.png)

![image](https://user-images.githubusercontent.com/30112738/29769274-d9bbe592-8c13-11e7-87b6-e6e9dd002e44.png)

![image](https://user-images.githubusercontent.com/30112738/29769390-546b4bfc-8c14-11e7-85ee-b97cb058a1e2.png)

**Comment by benjaminl83** [comment]
@Ponpimonk 
This could be overlapping of cells.
Can you check if there is a cell underneath?

**Comment by Ponpimonk** [comment]
@benjaminl83 I try to delete and expand to  ensure no cell is underneath. But the result is very confusing. Please go to this link.
https://raimon-land-sales-matrix.firebaseapp.com/building/edit/-KscFy8f-dsMWv7e1Wj8

**Comment by purnomoeko** [comment]
@Ponpimonk 

this issue need to be cleared in training session. because it's hard to visualize what you experienced.

**Comment by chuanhiang** [comment]
@Ponpimonk 

This is not a bug, you just need to be familiar with editing the grid lines. If this is an issue I won't be able to draw the elevations for The Loft Asoke.

Please close this issue

Thanks.

**Comment by Ponpimonk** [comment]
OK
