### ISSUE TITLE
No price information show up

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#82]
@benjaminl83 @purnomoeko 

https://raimon-land-sales-matrix.firebaseapp.com/building/edit/-KscFy8f-dsMWv7e1Wj8

![image](https://user-images.githubusercontent.com/30112738/29769731-c8d3ec00-8c15-11e7-8feb-4d2eaf7d19c9.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

I tried it and it is showing. Let's monitor this situation.

![image](https://user-images.githubusercontent.com/9443519/29773530-78109096-8c30-11e7-89cd-c5f5b6012010.png)

**Comment by purnomoeko** [comment]
If the grid is not big enough we won't show the price. please consider to make the grid big enough to contain the price info

**Comment by Ponpimonk** [comment]
OK
![image](https://user-images.githubusercontent.com/30112738/29867370-8b4e2b16-8da5-11e7-8048-85e4369c57aa.png)
