### ISSUE TITLE
Query Color Issue

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#83]
@benjaminl83 @purnomoeko 

The color changes incorrectly when there are more than 1 filter involved.
Filter color were set and display as follows:
Filter 1 set = yellow, result = green
Filter 2 set = blue, result = blue
Filter 3 set = green, result = yellow

https://raimon-land-sales-matrix.firebaseapp.com/query/edit/-KsHKKChvcYJn_pA9ibI/-KsHVQXsJEOsIG9d9saU

![image](https://user-images.githubusercontent.com/30112738/29770239-39d96ec8-8c18-11e7-885c-5b8652e63bfb.png)

**Comment by Ponpimonk** [comment]
@purnomoeko @benjaminl83 

The problem with query regarding the color coding is when we start to use "Filter 3" you color switch by itself. If I work between 2 filters, the color will show correctly.

**Comment by chuanhiang** [comment]
@purnomoeko 

The colour is not working for transfer status
![image](https://user-images.githubusercontent.com/9443519/29822681-dc8ed432-8cfe-11e7-96c6-236e028124fb.png)
![image](https://user-images.githubusercontent.com/9443519/29822687-e2f50cce-8cfe-11e7-97d1-d6bf32f0aea2.png)

The transfer status = Tentative is not showing

**Comment by chuanhiang** [comment]
@purnomoeko 
Now it is showing
![image](https://user-images.githubusercontent.com/9443519/29822884-90c8effa-8cff-11e7-9c53-227227f811ff.png)

This function requires monitoring.

Thanks.

**Comment by chuanhiang** [comment]
Sorry, issue not opened by me.

**Comment by Ponpimonk** [comment]
OK
