### ISSUE TITLE
Query Sales Status showing incorrect results

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#85]
@benjaminl83 @purnomoeko 

Filter 1: Sales status = Available = Green
Filter 2: Sales status = Sold = yellow

Results: LA-2505 = green but actually the unit status in Sandbox is available
LA-2905 = yellow but the unit status in Sandbox is Not Available.

![image](https://user-images.githubusercontent.com/30112738/29770931-808fbf90-8c1b-11e7-89f1-3396004e82f5.png)

![image](https://user-images.githubusercontent.com/30112738/29770942-8e719b56-8c1b-11e7-8694-16d39cc2b06d.png)

![image](https://user-images.githubusercontent.com/30112738/29770960-aa88ffe6-8c1b-11e7-9b65-1cd8809596c6.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

We tried the following:
Filter 1 = Sales Status = Available
Filter 2 = Sales Status = Sold
Filter 3 = Sales Status = Hold

After applying the second filter the result is correct and after applying the third filter it is still showing correct results.

![image](https://user-images.githubusercontent.com/9443519/29772680-69f66f52-8c2c-11e7-84a1-6a257d6ea08b.png)

**Comment by chuanhiang** [comment]
@purnomoeko 

The filter and colour code is correct now.

However, when the unit Sales Status = Sold we have to show the respective values 
Net Unit Price - top right corner
Net Price / Sq - bottom right corner
Sold Area - bottom left corner

Please try to get this one right. They are very particular about this.
Thanks.

**Comment by Ponpimonk** [comment]
OK
