### ISSUE TITLE
Query Issue - Quota display

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#86]
@purnomoeko @benjaminl83 Why is quota showing on the right handside corner? The quota should be displayed by color only, no need to show.

![image](https://user-images.githubusercontent.com/30112738/29771443-f52636b6-8c1d-11e7-832b-c4c064a12236.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please check, it is correct now.

Thanks.

**Comment by Ponpimonk** [comment]
OK

![image](https://user-images.githubusercontent.com/30112738/29867071-a1a5e602-8da4-11e7-9657-bbc9660086a2.png)
