### ISSUE TITLE
Query - Price positioning different from the Property Management & Area does not show

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#87]
@benjaminl83 @purnomoeko 

Why the price positioning is on the top right corner when I view the building in Query?
The price position, P/sqm, Area should stay in the same position whether I view the building via property management or query.

Also why there is no area showing ? US-502 has a title deed area = 25 sqm but the cell is not showing.

![image](https://user-images.githubusercontent.com/30112738/29771784-ad5b5544-8c1f-11e7-9fbe-15898d8557bb.png)

Query:
![image](https://user-images.githubusercontent.com/30112738/29771612-f76fb19e-8c1e-11e7-8392-331f390d8ae4.png)

Property Management:
![image](https://user-images.githubusercontent.com/30112738/29771641-25737d64-8c1f-11e7-9c60-91885ce60b27.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please check this issue, the results are correct now.

Thanks.

**Comment by Ponpimonk** [comment]
OK

![image](https://user-images.githubusercontent.com/30112738/29867236-12c2b586-8da5-11e7-865e-f0f4d26e7e1d.png)
