### ISSUE TITLE
Query -Unable to save

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#89]
@benjaminl83 @chuanhiang @purnomoeko 

I have saved this query before. I didn't make a change to the name. But suddenly I cannot save.

https://raimon-land-sales-matrix.firebaseapp.com/query/edit/-KsHKKChvcYJn_pA9ibI/-KscbjpfmV_cIbjAbvk1

![image](https://user-images.githubusercontent.com/30112738/29772134-821a3a4c-8c21-11e7-9e77-d988703c8cba.png)

**Comment by Ponpimonk** [comment]
I have just repeated the same step and I can now save.

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please test again and you should be able to save now.

![image](https://user-images.githubusercontent.com/9443519/29850736-46ec1d5e-8d62-11e7-842f-446f72073c6e.png)

**Comment by Ponpimonk** [comment]
OK
