### ISSUE TITLE
Web App Reporting - Adding Salesforce link in the popup window when right clicking the linked cell

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#90]
@purnomoeko 

Please try to make this function available as soon as you can so it is easier for us to compare the data between the cell and Salesforce record.

Thanks.

**Comment by purnomoeko** [comment]
@chuanhiang You can click unit name to go to salesforce.

**Comment by purnomoeko** [comment]
@chuanhiang You can click unit name to go to salesforce.

**Comment by chuanhiang** [comment]
@purnomoeko 

This link is active in linking the cell but not in web reporting. It is web reporting that is also required.

Thanks.

**Comment by benjaminl83** [comment]
Confirmed, link is working and will be shown as blue clickable link
![image](https://user-images.githubusercontent.com/18274902/29853154-d08ab4ae-8d70-11e7-8f99-920ecc20ca97.png)

**Comment by chuanhiang** [comment]
Resolved.
