### ISSUE TITLE
Web App Admin - Management user can still access property management

### ISSUE THREAD

**Issue by chuanhiang** [Interaktivtechnology/Raimon-Web#91]
@fransjosua

This is still not working.

Please login using:

Username: leoteng.ch@gmail.com
PW: interaktiv.1

User still can access property management.

Thanks.

**Comment by benjaminl83** [comment]
@chuanhiang 
May need to clear cache too.
Now I try its working. I get an error like such
![image](https://user-images.githubusercontent.com/18274902/29855960-47d3bb6c-8d82-11e7-99fa-8abbba86ea94.png)

**Comment by chuanhiang** [comment]
@benjaminl83 

Ok noted.

Thanks.

**Comment by Ponpimonk** [comment]
Ok
