### ISSUE TITLE
Hiding Property Management + User Management Bar for "Management User"

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#92]
@benjaminl83 @chuanhiang @purnomoeko 

Can  we hide 1) Property Management 2) User Management for "Management user"?

![image](https://user-images.githubusercontent.com/30112738/29856238-b52a2ea0-8d7b-11e7-9cf2-0575541056e2.png)

**Comment by chuanhiang** [comment]
@Ponpimonk 

Please check and close the issue if its working on your side.

Thanks.

![image](https://user-images.githubusercontent.com/9443519/29863368-1317501c-8da2-11e7-9bd9-2c6649b549ef.png)

**Comment by Ponpimonk** [comment]
OK
