### ISSUE TITLE
Booked Unit should work the same way as SOLD unit

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#94]
@benjaminl83 @purnomoeko 

The cell which the unit = booked should work just like the cell with sold unit
1. Showing "Net Unit Price + Furniture"
2. Showing "Net P/sqm"
3. Showing "sold area"

Do not show:
1. Title Deed Price
2. P/sqm
3. Title Deed Area

**Comment by chuanhiang** [comment]
@Ponpimonk 

Are you referring to the mobile app or web app?

Thanks.

**Comment by Ponpimonk** [comment]
@chuanhiang @purnomoeko @benjaminl83 

Web App --> The booked unit should show net unit + furniture price.
But instead it is showing "Title Deed Price"

https://rl--full.cs31.my.salesforce.com/01t900000008mcT

![image](https://user-images.githubusercontent.com/30112738/29866926-24b2b95e-8da4-11e7-9113-0fe345a8c558.png)

**Comment by Ponpimonk** [comment]
OK
![image](https://user-images.githubusercontent.com/30112738/29910486-5c700f4e-8e54-11e7-9ce4-8dae534a229d.png)


![image](https://user-images.githubusercontent.com/30112738/29910513-709450b6-8e54-11e7-8e50-ebd997a26c34.png)
