### ISSUE TITLE
Query - Filtering by Transfer Date

### ISSUE THREAD

**Issue by Ponpimonk** [Interaktivtechnology/Raimon-Web#98]
https://github.com/Interaktivtechnology/Raimon-Web

How do we filter by transfer date?

@benjaminl83 @purnomoeko @chuanhiang

**Comment by purnomoeko** [comment]
@Ponpimonk this issue has been solved please check

**Comment by Ponpimonk** [comment]
@purnomoeko @benjaminl83 US-503 transfer date = 14 July 2016. However this color mapping does not show in the query. Pls check.

https://raimon-land-sales-matrix.firebaseapp.com/query/edit/-KsHKKChvcYJn_pA9ibI/-KscbjpfmV_cIbjAbvk1

![image](https://user-images.githubusercontent.com/30112738/30011273-2874112c-9160-11e7-8a4c-180157a92fd2.png)


![image](https://user-images.githubusercontent.com/30112738/30011250-08a5cf2a-9160-11e7-9029-f23b0c5e63ea.png)

**Comment by purnomoeko** [comment]
Hi @Ponpimonk, 

We got it right, maybe you need to refresh the page. 


![screen shot 2017-09-04 at 11 05 45 am](https://user-images.githubusercontent.com/3125614/30011389-30144efa-9161-11e7-9950-1a204a45f01e.png)

**Comment by Ponpimonk** [comment]
Hi. I tried again and now it is hi-lighting the other unit.
![image](https://user-images.githubusercontent.com/30112738/30018287-826de68c-9186-11e7-893f-efcab0abea98.png)

**Comment by Ponpimonk** [comment]
https://rl--full.cs31.my.salesforce.com/01t90000000lamMAAQ

**Comment by Ponpimonk** [comment]
Ok it works
